version: '3'

tasks:
  install-goyacc:
    desc: Install GoYACC parser generator
    cmds:
      - go install golang.org/x/tools/cmd/goyacc@latest
      - 'echo "GoYACC installed. To compile .y files, use: goyacc <path-to-y-file>"'

  install-prereqs:
    desc: Install all prerequisites
    cmds:
      - task: install-goyacc

  generate:
    desc: Generates all project stuff
    cmds:
      - go generate ./...
