// Code generated by goyacc -o parser.go berksfile.y. DO NOT EDIT.

//line berksfile.y:4

package berksfileparser

import __yyfmt__ "fmt"

//line berksfile.y:5

import (
	"strings"
)

// Berksfile represents a parsed Berksfile DSL root.
type Berksfile struct {
	Sources   []*Source
	Metadata  bool
	Cookbooks []*Cookbook
	Groups    []*Group
}

// Source defines a cookbook source (supermarket, chef_server, artifactory, etc).
type Source struct {
	Type    string            // e.g. "chef_server", "supermarket"
	URL     string            // e.g. "https://chef.example.com"
	Options map[string]string // e.g. user, client_key, api_key
}

// Cookbook represents a cookbook declaration.
type Cookbook struct {
	Name    string            // cookbook name
	Version string            // version constraint, e.g. "~> 1.2"
	Options map[string]string // git, branch, path, etc.
	Groups  []string          // group names, empty if none
}

// Group represents a named group block with multiple cookbooks.
type Group struct {
	Name      string
	Cookbooks []*Cookbook
}

var Result *Berksfile

func trimQuotes(s string) string {
	return strings.Trim(s, `"'`)
}

// Intermediate types for semantic values
type sourceArgs struct {
	typ  string
	url  string
	opts map[string]string
}

type cbTail struct {
	version string
	options map[string]string
}

type kv struct {
	key   string
	value string
}

// Collections type to hold multiple items with metadata flag
type collections struct {
	sources   []*Source
	cookbooks []*Cookbook
	groups    []*Group
	metadata  bool
}

// Statement result type
type stmtResult struct {
	source   *Source
	cookbook *Cookbook
	group    *Group
	metadata bool
}

//line berksfile.y:81
type yySymType struct {
	yys         int
	str         string
	source      *Source
	cookbook    *Cookbook
	group       *Group
	sources     []*Source
	cookbooks   []*Cookbook
	groups      []*Group
	opts        map[string]string
	sa          sourceArgs
	cbTail      cbTail
	kv          kv
	boolVal     bool
	collections collections
	stmt        stmtResult
}

const SOURCE = 57346
const METADATA = 57347
const COOKBOOK = 57348
const GROUP = 57349
const DO = 57350
const END = 57351
const IDENT = 57352
const STRING = 57353
const COLON = 57354
const COMMA = 57355
const LBRACE = 57356
const RBRACE = 57357
const HASHROCKET = 57358
const NEWLINE = 57359

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SOURCE",
	"METADATA",
	"COOKBOOK",
	"GROUP",
	"DO",
	"END",
	"IDENT",
	"STRING",
	"COLON",
	"COMMA",
	"LBRACE",
	"RBRACE",
	"HASHROCKET",
	"NEWLINE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line berksfile.y:381

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 79

var yyAct = [...]int8{
	42, 31, 32, 58, 12, 8, 46, 10, 11, 12,
	13, 10, 11, 12, 13, 61, 12, 39, 43, 66,
	15, 33, 41, 34, 5, 52, 38, 49, 44, 39,
	55, 37, 40, 33, 29, 34, 23, 30, 25, 51,
	53, 48, 48, 50, 26, 27, 56, 33, 41, 34,
	22, 21, 20, 60, 63, 18, 17, 64, 65, 57,
	54, 28, 45, 62, 59, 36, 35, 4, 47, 9,
	24, 14, 19, 7, 16, 6, 3, 2, 1,
}

var yyPact = [...]int16{
	7, -1000, -1000, 3, -1000, -1000, -1000, -1000, -1000, -1000,
	45, -1000, 41, 38, -1000, -1000, -1000, -1000, 24, 25,
	-1000, -1000, 34, 50, -1000, 23, 58, 57, 18, 13,
	37, -1000, 5, 16, 52, 10, 10, 37, 11, 49,
	15, 1, -1000, 37, 48, -13, 55, -2, -1000, -1000,
	54, -1000, 37, -1000, -1000, -1000, 5, -1000, 47, -1000,
	-1000, -1000, -1000, 4, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 78, 77, 76, 67, 75, 74, 73, 5, 72,
	70, 69, 6, 68, 1, 0, 2,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 4, 4,
	4, 4, 5, 6, 6, 6, 7, 8, 9, 9,
	10, 10, 10, 10, 10, 10, 11, 11, 12, 12,
	13, 13, 13, 13, 14, 15, 15, 16, 16, 16,
}

var yyR2 = [...]int8{
	0, 1, 1, 0, 2, 2, 1, 1, 1, 1,
	1, 1, 2, 1, 3, 5, 1, 3, 1, 1,
	2, 4, 6, 2, 4, 0, 6, 6, 1, 0,
	2, 2, 1, 1, 2, 3, 0, 3, 4, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, 17, -5, -7, -8, -11,
	4, 5, 6, 7, -4, 17, -6, 11, 10, -9,
	11, 10, 12, 12, -10, 13, 10, 11, 11, 11,
	14, -14, -16, 10, 12, 8, 8, 13, 13, 16,
	-14, 11, -15, 13, 12, 10, -12, -13, -8, 17,
	-12, -14, 14, -14, 11, 15, -16, 11, 16, 9,
	-8, 17, 9, -14, -15, 11, 15,
}

var yyDef = [...]int8{
	3, -2, 1, 2, 6, 7, 8, 9, 10, 11,
	0, 16, 0, 0, 4, 5, 12, 13, 0, 25,
	18, 19, 0, 0, 17, 0, 0, 0, 14, 20,
	0, 23, 36, 0, 0, 29, 29, 0, 0, 0,
	0, 0, 34, 0, 0, 0, 0, 28, 32, 33,
	0, 15, 0, 24, 39, 21, 36, 37, 0, 26,
	30, 31, 27, 0, 35, 38, 22,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:118
		{
			Result = &Berksfile{
				Sources:   yyDollar[1].collections.sources,
				Metadata:  yyDollar[1].collections.metadata,
				Cookbooks: yyDollar[1].collections.cookbooks,
				Groups:    yyDollar[1].collections.groups,
			}
			yyVAL.collections = yyDollar[1].collections
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:130
		{
			yyVAL.collections = yyDollar[1].collections
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:133
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*Cookbook{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:142
		{
			yyVAL.collections.sources = yyDollar[1].collections.sources
			yyVAL.collections.cookbooks = yyDollar[1].collections.cookbooks
			yyVAL.collections.groups = yyDollar[1].collections.groups
			yyVAL.collections.metadata = yyDollar[1].collections.metadata

			// Add new statement
			if yyDollar[2].stmt.source != nil {
				yyVAL.collections.sources = append(yyVAL.collections.sources, yyDollar[2].stmt.source)
			}
			if yyDollar[2].stmt.cookbook != nil {
				yyVAL.collections.cookbooks = append(yyVAL.collections.cookbooks, yyDollar[2].stmt.cookbook)
			}
			if yyDollar[2].stmt.group != nil {
				yyVAL.collections.groups = append(yyVAL.collections.groups, yyDollar[2].stmt.group)
			}
			if yyDollar[2].stmt.metadata {
				yyVAL.collections.metadata = true
			}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:162
		{
			yyVAL.collections = yyDollar[1].collections
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:165
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*Cookbook{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false

			// Add the statement
			if yyDollar[1].stmt.source != nil {
				yyVAL.collections.sources = append(yyVAL.collections.sources, yyDollar[1].stmt.source)
			}
			if yyDollar[1].stmt.cookbook != nil {
				yyVAL.collections.cookbooks = append(yyVAL.collections.cookbooks, yyDollar[1].stmt.cookbook)
			}
			if yyDollar[1].stmt.group != nil {
				yyVAL.collections.groups = append(yyVAL.collections.groups, yyDollar[1].stmt.group)
			}
			if yyDollar[1].stmt.metadata {
				yyVAL.collections.metadata = true
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:185
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*Cookbook{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:194
		{
			yyVAL.stmt.source = yyDollar[1].source
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = false
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:200
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = yyDollar[1].boolVal
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:206
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = yyDollar[1].cookbook
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = false
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:212
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = yyDollar[1].group
			yyVAL.stmt.metadata = false
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:221
		{
			yyVAL.source = &Source{
				Type:    yyDollar[2].sa.typ,
				URL:     yyDollar[2].sa.url,
				Options: yyDollar[2].sa.opts,
			}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:231
		{
			yyVAL.sa.typ = "supermarket"
			yyVAL.sa.url = trimQuotes(yyDollar[1].str)
			yyVAL.sa.opts = nil
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:236
		{
			yyVAL.sa.typ = yyDollar[1].str
			yyVAL.sa.url = trimQuotes(yyDollar[3].str)
			yyVAL.sa.opts = nil
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line berksfile.y:241
		{
			yyVAL.sa.typ = yyDollar[1].str
			yyVAL.sa.url = trimQuotes(yyDollar[3].str)
			yyVAL.sa.opts = yyDollar[5].opts
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:249
		{
			yyVAL.boolVal = true
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:255
		{
			yyVAL.cookbook = &Cookbook{
				Name:    yyDollar[2].str,
				Version: yyDollar[3].cbTail.version,
				Options: yyDollar[3].cbTail.options,
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:265
		{
			yyVAL.str = trimQuotes(yyDollar[1].str)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:266
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:270
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = nil
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:274
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = yyDollar[3].opts
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line berksfile.y:278
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = yyDollar[5].opts
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:282
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = yyDollar[2].opts
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:286
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = yyDollar[4].opts
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:290
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = nil
		}
	case 26:
		yyDollar = yyS[yypt-6 : yypt+1]
//line berksfile.y:297
		{
			groupName := yyDollar[3].str
			for _, cb := range yyDollar[5].cookbooks {
				cb.Groups = append(cb.Groups, groupName)
			}
			yyVAL.group = &Group{
				Name:      groupName,
				Cookbooks: yyDollar[5].cookbooks,
			}
		}
	case 27:
		yyDollar = yyS[yypt-6 : yypt+1]
//line berksfile.y:307
		{
			groupName := trimQuotes(yyDollar[3].str)
			for _, cb := range yyDollar[5].cookbooks {
				cb.Groups = append(cb.Groups, groupName)
			}
			yyVAL.group = &Group{
				Name:      groupName,
				Cookbooks: yyDollar[5].cookbooks,
			}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:320
		{
			yyVAL.cookbooks = yyDollar[1].cookbooks
		}
	case 29:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:323
		{
			yyVAL.cookbooks = []*Cookbook{}
		}
	case 30:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:329
		{
			yyVAL.cookbooks = append(yyDollar[1].cookbooks, yyDollar[2].cookbook)
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:332
		{
			yyVAL.cookbooks = yyDollar[1].cookbooks
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:335
		{
			yyVAL.cookbooks = []*Cookbook{yyDollar[1].cookbook}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:338
		{
			yyVAL.cookbooks = []*Cookbook{}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:344
		{
			m := map[string]string{yyDollar[1].kv.key: yyDollar[1].kv.value}
			for k, v := range yyDollar[2].opts {
				m[k] = v
			}
			yyVAL.opts = m
		}
	case 35:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:354
		{
			m := map[string]string{yyDollar[2].kv.key: yyDollar[2].kv.value}
			for k, v := range yyDollar[3].opts {
				m[k] = v
			}
			yyVAL.opts = m
		}
	case 36:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:361
		{
			yyVAL.opts = map[string]string{}
		}
	case 37:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:367
		{
			yyVAL.kv.key = yyDollar[1].str
			yyVAL.kv.value = trimQuotes(yyDollar[3].str)
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:371
		{
			yyVAL.kv.key = yyDollar[2].str
			yyVAL.kv.value = trimQuotes(yyDollar[4].str)
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:375
		{
			yyVAL.kv.key = trimQuotes(yyDollar[1].str)
			yyVAL.kv.value = trimQuotes(yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
