// Code generated by goyacc -o parser.go berksfile.y. DO NOT EDIT.

//line berksfile.y:4

package berksfile

import __yyfmt__ "fmt"

//line berksfile.y:5

import (
	"strings"

	"github.com/bdwyertech/go-berkshelf/pkg/berkshelf"
)

// CookbookDef represents a cookbook definition in a Berksfile
type CookbookDef struct {
	Name       string
	Constraint *berkshelf.Constraint
	Source     *berkshelf.SourceLocation
	Groups     []string
}

// Berksfile represents a parsed Berksfile
type Berksfile struct {
	Sources     []*berkshelf.SourceLocation // List of default sources with full configuration
	Cookbooks   []*CookbookDef              // All cookbook definitions
	Groups      map[string][]*CookbookDef   // Grouped cookbooks
	HasMetadata bool                        // Whether metadata directive is present
}

var Result *Berksfile

// GetCookbooks returns all cookbooks, optionally filtered by groups
func (b *Berksfile) GetCookbooks(groups ...string) []*CookbookDef {
	if len(groups) == 0 {
		return b.Cookbooks
	}

	// Create a map to avoid duplicates
	cookbookMap := make(map[string]*CookbookDef)

	for _, group := range groups {
		if groupCookbooks, ok := b.Groups[group]; ok {
			for _, cookbook := range groupCookbooks {
				cookbookMap[cookbook.Name] = cookbook
			}
		}
	}

	// Convert map to slice
	result := make([]*CookbookDef, 0, len(cookbookMap))
	for _, cookbook := range cookbookMap {
		result = append(result, cookbook)
	}

	return result
}

// GetCookbook returns a specific cookbook by name
func (b *Berksfile) GetCookbook(name string) *CookbookDef {
	for _, cookbook := range b.Cookbooks {
		if cookbook.Name == name {
			return cookbook
		}
	}
	return nil
}

// HasGroup checks if a group exists
func (b *Berksfile) HasGroup(name string) bool {
	_, ok := b.Groups[name]
	return ok
}

// GetGroups returns all group names
func (b *Berksfile) GetGroups() []string {
	groups := make([]string, 0, len(b.Groups))
	for group := range b.Groups {
		groups = append(groups, group)
	}
	return groups
}

// ParseConstraint parses a version constraint string
func ParseConstraint(constraintStr string) (*berkshelf.Constraint, error) {
	return berkshelf.NewConstraint(constraintStr)
}

func trimQuotes(s string) string {
	return strings.Trim(s, `"'`)
}

// Intermediate types for semantic values
type sourceArgs struct {
	typ  string
	url  string
	opts map[string]string
}

type cbTail struct {
	version string
	options map[string]string
}

type kv struct {
	key   string
	value string
}

// Source represents a source definition in a Berksfile
type Source struct {
	Type    string
	URL     string
	Options map[string]string
}

// Group represents a group definition in a Berksfile
type Group struct {
	Name      string
	Cookbooks []*CookbookDef
}

// Collections type to hold multiple items with metadata flag
type collections struct {
	sources   []*Source
	cookbooks []*CookbookDef
	groups    []*Group
	metadata  bool
}

// Statement result type
type stmtResult struct {
	source   *Source
	cookbook *CookbookDef
	group    *Group
	metadata bool
}

//line berksfile.y:139
type yySymType struct {
	yys         int
	str         string
	source      *Source
	cookbook    *CookbookDef
	group       *Group
	sources     []*Source
	cookbooks   []*CookbookDef
	groups      []*Group
	opts        map[string]string
	sa          sourceArgs
	cbTail      cbTail
	kv          kv
	boolVal     bool
	collections collections
	stmt        stmtResult
}

const SOURCE = 57346
const METADATA = 57347
const COOKBOOK = 57348
const GROUP = 57349
const DO = 57350
const END = 57351
const IDENT = 57352
const STRING = 57353
const COLON = 57354
const COMMA = 57355
const LBRACE = 57356
const RBRACE = 57357
const HASHROCKET = 57358
const NEWLINE = 57359

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SOURCE",
	"METADATA",
	"COOKBOOK",
	"GROUP",
	"DO",
	"END",
	"IDENT",
	"STRING",
	"COLON",
	"COMMA",
	"LBRACE",
	"RBRACE",
	"HASHROCKET",
	"NEWLINE",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line berksfile.y:554

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 82

var yyAct = [...]int8{
	50, 36, 37, 8, 10, 11, 12, 13, 10, 11,
	12, 13, 12, 12, 66, 47, 70, 15, 38, 49,
	39, 5, 60, 56, 43, 46, 63, 51, 47, 45,
	38, 34, 39, 42, 35, 28, 52, 48, 38, 49,
	39, 29, 23, 24, 25, 55, 30, 59, 61, 57,
	58, 54, 44, 26, 64, 31, 32, 21, 20, 18,
	17, 69, 67, 65, 62, 68, 33, 53, 4, 22,
	41, 40, 14, 9, 27, 19, 7, 16, 6, 3,
	2, 1,
}

var yyPact = [...]int16{
	4, -1000, -1000, 0, -1000, -1000, -1000, -1000, -1000, -1000,
	49, -1000, 47, 32, -1000, -1000, -1000, -1000, 41, 22,
	-1000, -1000, 33, -1000, -1000, 45, 55, -1000, 20, 7,
	40, -1000, -1000, 16, 12, 28, -1000, 14, 24, 57,
	42, 6, -1000, -1000, 39, 28, 8, 53, 11, -1,
	-1000, 28, 52, -2, -1000, -1000, -1000, -1000, -1000, -1000,
	28, -1000, -1000, -1000, 14, -1000, 50, 1, -1000, -1000,
	-1000,
}

var yyPgo = [...]int8{
	0, 81, 80, 79, 68, 78, 77, 76, 3, 75,
	74, 73, 71, 70, 1, 0, 2, 69,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 4, 4,
	4, 4, 5, 6, 6, 6, 7, 8, 9, 9,
	10, 10, 10, 10, 10, 10, 11, 17, 17, 17,
	17, 17, 17, 12, 12, 13, 13, 13, 13, 14,
	15, 15, 16, 16, 16,
}

var yyR2 = [...]int8{
	0, 1, 1, 0, 2, 2, 1, 1, 1, 1,
	1, 1, 2, 1, 3, 5, 1, 3, 1, 1,
	2, 4, 6, 2, 4, 0, 5, 4, 4, 1,
	1, 2, 2, 1, 0, 2, 2, 1, 1, 2,
	3, 0, 3, 4, 3,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, 17, -5, -7, -8, -11,
	4, 5, 6, 7, -4, 17, -6, 11, 10, -9,
	11, 10, -17, 10, 11, 12, 12, -10, 13, 8,
	13, 10, 11, 11, 11, 14, -14, -16, 10, 12,
	-12, -13, -8, 17, 12, 13, 13, 16, -14, 11,
	-15, 13, 12, 10, 9, -8, 17, 10, 11, -14,
	14, -14, 11, 15, -16, 11, 16, -14, -15, 11,
	15,
}

var yyDef = [...]int8{
	3, -2, 1, 2, 6, 7, 8, 9, 10, 11,
	0, 16, 0, 0, 4, 5, 12, 13, 0, 25,
	18, 19, 0, 29, 30, 0, 0, 17, 0, 34,
	0, 31, 32, 14, 20, 0, 23, 41, 0, 0,
	0, 33, 37, 38, 0, 0, 0, 0, 0, 0,
	39, 0, 0, 0, 26, 35, 36, 27, 28, 15,
	0, 24, 44, 21, 41, 42, 0, 0, 40, 43,
	22,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:177
		{
			// Convert sources from []*Source to []*berkshelf.SourceLocation
			sources := make([]*berkshelf.SourceLocation, len(yyDollar[1].collections.sources))
			for i, src := range yyDollar[1].collections.sources {
				// Convert map[string]string to map[string]any
				options := make(map[string]any)
				for k, v := range src.Options {
					options[k] = v
				}

				sources[i] = &berkshelf.SourceLocation{
					Type:    src.Type,
					URL:     src.URL,
					Options: options,
				}
			}

			// Collect all cookbooks (both standalone and from groups)
			allCookbooks := make([]*CookbookDef, 0, len(yyDollar[1].collections.cookbooks))
			allCookbooks = append(allCookbooks, yyDollar[1].collections.cookbooks...)

			// Convert groups from []*Group to map[string][]*CookbookDef
			groups := make(map[string][]*CookbookDef)
			for _, group := range yyDollar[1].collections.groups {
				// Add group cookbooks to the main cookbook list
				allCookbooks = append(allCookbooks, group.Cookbooks...)

				// Handle group names (could be comma-separated for multiple groups)
				groupNames := strings.Split(group.Name, ",")

				for _, groupName := range groupNames {
					groupName = strings.TrimSpace(groupName)
					if groups[groupName] == nil {
						groups[groupName] = []*CookbookDef{}
					}

					// Add cookbooks to this group
					for _, cb := range group.Cookbooks {
						// Check if cookbook already exists in this group
						found := false
						for _, existing := range groups[groupName] {
							if existing.Name == cb.Name {
								found = true
								break
							}
						}
						if !found {
							groups[groupName] = append(groups[groupName], cb)
						}
					}
				}
			}

			Result = &Berksfile{
				Sources:     sources,
				Cookbooks:   allCookbooks,
				Groups:      groups,
				HasMetadata: yyDollar[1].collections.metadata,
			}
			yyVAL.collections = yyDollar[1].collections
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:241
		{
			yyVAL.collections = yyDollar[1].collections
		}
	case 3:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:244
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*CookbookDef{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:253
		{
			yyVAL.collections.sources = yyDollar[1].collections.sources
			yyVAL.collections.cookbooks = yyDollar[1].collections.cookbooks
			yyVAL.collections.groups = yyDollar[1].collections.groups
			yyVAL.collections.metadata = yyDollar[1].collections.metadata

			// Add new statement
			if yyDollar[2].stmt.source != nil {
				yyVAL.collections.sources = append(yyVAL.collections.sources, yyDollar[2].stmt.source)
			}
			if yyDollar[2].stmt.cookbook != nil {
				yyVAL.collections.cookbooks = append(yyVAL.collections.cookbooks, yyDollar[2].stmt.cookbook)
			}
			if yyDollar[2].stmt.group != nil {
				yyVAL.collections.groups = append(yyVAL.collections.groups, yyDollar[2].stmt.group)
			}
			if yyDollar[2].stmt.metadata {
				yyVAL.collections.metadata = true
			}
		}
	case 5:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:273
		{
			yyVAL.collections = yyDollar[1].collections
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:276
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*CookbookDef{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false

			// Add the statement
			if yyDollar[1].stmt.source != nil {
				yyVAL.collections.sources = append(yyVAL.collections.sources, yyDollar[1].stmt.source)
			}
			if yyDollar[1].stmt.cookbook != nil {
				yyVAL.collections.cookbooks = append(yyVAL.collections.cookbooks, yyDollar[1].stmt.cookbook)
			}
			if yyDollar[1].stmt.group != nil {
				yyVAL.collections.groups = append(yyVAL.collections.groups, yyDollar[1].stmt.group)
			}
			if yyDollar[1].stmt.metadata {
				yyVAL.collections.metadata = true
			}
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:296
		{
			yyVAL.collections.sources = []*Source{}
			yyVAL.collections.cookbooks = []*CookbookDef{}
			yyVAL.collections.groups = []*Group{}
			yyVAL.collections.metadata = false
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:305
		{
			yyVAL.stmt.source = yyDollar[1].source
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = false
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:311
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = yyDollar[1].boolVal
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:317
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = yyDollar[1].cookbook
			yyVAL.stmt.group = nil
			yyVAL.stmt.metadata = false
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:323
		{
			yyVAL.stmt.source = nil
			yyVAL.stmt.cookbook = nil
			yyVAL.stmt.group = yyDollar[1].group
			yyVAL.stmt.metadata = false
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:332
		{
			yyVAL.source = &Source{
				Type:    yyDollar[2].sa.typ,
				URL:     yyDollar[2].sa.url,
				Options: yyDollar[2].sa.opts,
			}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:342
		{
			yyVAL.sa.typ = "supermarket"
			yyVAL.sa.url = trimQuotes(yyDollar[1].str)
			yyVAL.sa.opts = nil
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:347
		{
			yyVAL.sa.typ = yyDollar[1].str
			yyVAL.sa.url = trimQuotes(yyDollar[3].str)
			yyVAL.sa.opts = nil
		}
	case 15:
		yyDollar = yyS[yypt-5 : yypt+1]
//line berksfile.y:352
		{
			yyVAL.sa.typ = yyDollar[1].str
			yyVAL.sa.url = trimQuotes(yyDollar[3].str)
			yyVAL.sa.opts = yyDollar[5].opts
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:360
		{
			yyVAL.boolVal = true
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:366
		{
			constraint, _ := ParseConstraint(">= 0.0.0")
			if yyDollar[3].cbTail.version != "" {
				if c, err := ParseConstraint(yyDollar[3].cbTail.version); err != nil {
					yylex.Error("invalid version constraint: " + yyDollar[3].cbTail.version)
					return 1
				} else {
					constraint = c
				}
			}

			source := &berkshelf.SourceLocation{}
			if yyDollar[3].cbTail.options != nil {
				source.Options = make(map[string]any)
				if gitUrl, ok := yyDollar[3].cbTail.options["git"]; ok {
					source.Type = "git"
					source.URL = gitUrl
					if branch, ok := yyDollar[3].cbTail.options["branch"]; ok {
						source.Ref = branch
						source.Options["branch"] = branch
					}
					if ref, ok := yyDollar[3].cbTail.options["ref"]; ok {
						source.Ref = ref
						source.Options["ref"] = ref
					}
				} else if github, ok := yyDollar[3].cbTail.options["github"]; ok {
					source.Type = "git"
					source.URL = "https://github.com/" + github + ".git"
				} else if path, ok := yyDollar[3].cbTail.options["path"]; ok {
					source.Type = "path"
					source.Path = path
				}
			}

			yyVAL.cookbook = &CookbookDef{
				Name:       yyDollar[2].str,
				Constraint: constraint,
				Source:     source,
				Groups:     []string{},
			}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:410
		{
			yyVAL.str = trimQuotes(yyDollar[1].str)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:411
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:415
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = nil
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:419
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = yyDollar[3].opts
		}
	case 22:
		yyDollar = yyS[yypt-6 : yypt+1]
//line berksfile.y:423
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = yyDollar[5].opts
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:427
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = yyDollar[2].opts
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:431
		{
			yyVAL.cbTail.version = trimQuotes(yyDollar[2].str)
			yyVAL.cbTail.options = yyDollar[4].opts
		}
	case 25:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:435
		{
			yyVAL.cbTail.version = ""
			yyVAL.cbTail.options = nil
		}
	case 26:
		yyDollar = yyS[yypt-5 : yypt+1]
//line berksfile.y:442
		{
			// For multiple groups, we need to create separate Group entries
			// but the cookbooks will be shared across groups
			groupNames := make([]string, len(yyDollar[2].sources))
			for i, src := range yyDollar[2].sources {
				groupNames[i] = src.URL // We're reusing Source.URL to store group names
			}

			// Add group names to each cookbook
			for _, cb := range yyDollar[4].cookbooks {
				cb.Groups = append(cb.Groups, groupNames...)
			}

			// For empty groups, we still need to return a Group object with the first name
			// The berksfile rule will handle creating entries for all group names
			groupName := groupNames[0]
			if len(groupNames) > 1 {
				// For multiple groups, we need to create a special marker
				// The berksfile rule will expand this into multiple group entries
				groupName = strings.Join(groupNames, ",")
			}

			yyVAL.group = &Group{
				Name:      groupName,
				Cookbooks: yyDollar[4].cookbooks,
			}
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:472
		{
			yyVAL.sources = append(yyDollar[1].sources, &Source{URL: yyDollar[4].str})
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:475
		{
			yyVAL.sources = append(yyDollar[1].sources, &Source{URL: trimQuotes(yyDollar[4].str)})
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:478
		{
			yyVAL.sources = []*Source{{URL: yyDollar[1].str}}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:481
		{
			yyVAL.sources = []*Source{{URL: trimQuotes(yyDollar[1].str)}}
		}
	case 31:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:484
		{
			yyVAL.sources = []*Source{{URL: yyDollar[2].str}}
		}
	case 32:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:487
		{
			yyVAL.sources = []*Source{{URL: trimQuotes(yyDollar[2].str)}}
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:493
		{
			yyVAL.cookbooks = yyDollar[1].cookbooks
		}
	case 34:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:496
		{
			yyVAL.cookbooks = []*CookbookDef{}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:502
		{
			yyVAL.cookbooks = append(yyDollar[1].cookbooks, yyDollar[2].cookbook)
		}
	case 36:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:505
		{
			yyVAL.cookbooks = yyDollar[1].cookbooks
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:508
		{
			yyVAL.cookbooks = []*CookbookDef{yyDollar[1].cookbook}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line berksfile.y:511
		{
			yyVAL.cookbooks = []*CookbookDef{}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line berksfile.y:517
		{
			m := map[string]string{yyDollar[1].kv.key: yyDollar[1].kv.value}
			for k, v := range yyDollar[2].opts {
				m[k] = v
			}
			yyVAL.opts = m
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:527
		{
			m := map[string]string{yyDollar[2].kv.key: yyDollar[2].kv.value}
			for k, v := range yyDollar[3].opts {
				m[k] = v
			}
			yyVAL.opts = m
		}
	case 41:
		yyDollar = yyS[yypt-0 : yypt+1]
//line berksfile.y:534
		{
			yyVAL.opts = map[string]string{}
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:540
		{
			yyVAL.kv.key = yyDollar[1].str
			yyVAL.kv.value = trimQuotes(yyDollar[3].str)
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line berksfile.y:544
		{
			yyVAL.kv.key = yyDollar[2].str
			yyVAL.kv.value = trimQuotes(yyDollar[4].str)
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line berksfile.y:548
		{
			yyVAL.kv.key = trimQuotes(yyDollar[1].str)
			yyVAL.kv.value = trimQuotes(yyDollar[3].str)
		}
	}
	goto yystack /* stack new state and value */
}
