// Code generated by goyacc -o parser.go policyfile.y. DO NOT EDIT.

//line policyfile.y:4

package policyfile

import __yyfmt__ "fmt"

//line policyfile.y:5

import (
	"strings"

	"github.com/bdwyer/go-berkshelf/pkg/berkshelf"
)

// CookbookDef represents a cookbook definition in a Policyfile.rb
type CookbookDef struct {
	Name       string
	Constraint *berkshelf.Constraint
	Source     *berkshelf.SourceLocation
}

// Policyfile represents a parsed Policyfile.rb (Berkshelf-equivalent parts only)
type Policyfile struct {
	DefaultSources []*berkshelf.SourceLocation // List of default sources
	Cookbooks      []*CookbookDef              // All cookbook definitions
}

var Result *Policyfile

// GetCookbooks returns all cookbooks
func (p *Policyfile) GetCookbooks() []*CookbookDef {
	return p.Cookbooks
}

//line policyfile.y:35
type yySymType struct {
	yys        int
	str        string
	constraint *berkshelf.Constraint
	source     *berkshelf.SourceLocation
	cookbook   *CookbookDef
	options    map[string]string
}

const IDENTIFIER = 57346
const STRING = 57347
const SYMBOL = 57348
const NEWLINE = 57349
const COMMA = 57350
const COLON = 57351
const DEFAULT_SOURCE = 57352
const COOKBOOK = 57353

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"SYMBOL",
	"NEWLINE",
	"COMMA",
	"COLON",
	"DEFAULT_SOURCE",
	"COOKBOOK",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line policyfile.y:249

// createSourceFromOptions creates a SourceLocation from cookbook options
func createSourceFromOptions(options map[string]string) *berkshelf.SourceLocation {
	if options == nil {
		return nil
	}

	// Handle different source types
	if path, ok := options["path"]; ok {
		return &berkshelf.SourceLocation{
			Type: "path",
			Path: path,
		}
	}

	if gitURL, ok := options["git"]; ok {
		source := &berkshelf.SourceLocation{
			Type: "git",
			URL:  gitURL,
		}

		// Add git-specific options
		if branch, ok := options["branch"]; ok {
			source.Ref = branch
		}
		if tag, ok := options["tag"]; ok {
			source.Ref = tag
		}
		if ref, ok := options["ref"]; ok {
			source.Ref = ref
		}

		return source
	}

	if github, ok := options["github"]; ok {
		source := &berkshelf.SourceLocation{
			Type: "git",
			URL:  "https://github.com/" + github + ".git",
		}

		// Add git-specific options
		if branch, ok := options["branch"]; ok {
			source.Ref = branch
		}
		if tag, ok := options["tag"]; ok {
			source.Ref = tag
		}
		if ref, ok := options["ref"]; ok {
			source.Ref = ref
		}

		return source
	}

	if chefServerURL, ok := options["chef_server"]; ok {
		source := &berkshelf.SourceLocation{
			Type: "chef_server",
			URL:  chefServerURL,
		}

		// Add chef server specific options to Options map
		if source.Options == nil {
			source.Options = make(map[string]any)
		}

		if clientName, ok := options["client_name"]; ok {
			source.Options["client_name"] = clientName
		}
		if clientKey, ok := options["client_key"]; ok {
			source.Options["client_key"] = clientKey
		}
		if nodeNameOpt, ok := options["node_name"]; ok {
			source.Options["node_name"] = nodeNameOpt
		}
		if validation_client_name, ok := options["validation_client_name"]; ok {
			source.Options["validation_client_name"] = validation_client_name
		}
		if validation_key, ok := options["validation_key"]; ok {
			source.Options["validation_key"] = validation_key
		}

		return source
	}

	if supermarketURL, ok := options["supermarket"]; ok {
		source := &berkshelf.SourceLocation{
			Type: "supermarket",
			URL:  supermarketURL,
		}

		// Add supermarket-specific options
		if source.Options == nil {
			source.Options = make(map[string]any)
		}

		if apiKey, ok := options["api_key"]; ok {
			source.Options["api_key"] = apiKey
		}

		return source
	}

	if artifactoryURL, ok := options["artifactory"]; ok {
		source := &berkshelf.SourceLocation{
			Type: "supermarket", // Artifactory is treated as supermarket-like
			URL:  artifactoryURL,
		}

		// Add artifactory-specific options
		if source.Options == nil {
			source.Options = make(map[string]any)
		}

		if apiKey, ok := options["artifactory_api_key"]; ok {
			source.Options["artifactory_api_key"] = apiKey
		}
		if identityToken, ok := options["artifactory_identity_token"]; ok {
			source.Options["artifactory_identity_token"] = identityToken
		}

		return source
	}

	// Handle other source types as needed
	return nil
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 2,
	1, 1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 33

var yyAct = [...]int8{
	29, 22, 7, 19, 31, 26, 25, 6, 13, 24,
	8, 9, 16, 15, 10, 23, 20, 30, 17, 14,
	23, 3, 2, 1, 21, 12, 18, 28, 27, 5,
	11, 4, 32,
}

var yyPact = [...]int16{
	-1000, -1000, 0, -1000, -1000, -1000, -1000, 7, 2, 14,
	-1000, -1000, 5, -1000, 4, 13, 11, -1000, 1, -1000,
	-1000, -2, -4, -1000, 16, 16, 12, -1000, -5, -1000,
	-1000, 12, -1000,
}

var yyPgo = [...]int8{
	0, 31, 30, 29, 26, 25, 3, 24, 1, 0,
	23, 22, 21,
}

var yyR1 = [...]int8{
	0, 10, 11, 11, 12, 12, 12, 12, 1, 2,
	2, 5, 3, 3, 3, 3, 6, 7, 7, 8,
	9, 4,
}

var yyR2 = [...]int8{
	0, 1, 0, 2, 1, 1, 1, 2, 2, 1,
	3, 1, 2, 4, 4, 6, 1, 3, 5, 1,
	1, 1,
}

var yyChk = [...]int16{
	-1000, -10, -11, -12, -1, -3, 7, 2, 10, 11,
	7, -2, -5, 6, 5, 8, 8, 5, -4, -6,
	5, -7, -8, 4, 8, 8, 9, -6, -8, -9,
	5, 9, -9,
}

var yyDef = [...]int8{
	2, -2, -2, 3, 4, 5, 6, 0, 0, 0,
	7, 8, 9, 11, 12, 0, 0, 10, 13, 14,
	21, 16, 0, 19, 0, 0, 0, 15, 0, 17,
	20, 0, 18,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:59
		{
			if Result == nil {
				Result = &Policyfile{
					DefaultSources: []*berkshelf.SourceLocation{},
					Cookbooks:      []*CookbookDef{},
				}
			}
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:74
		{
			if Result == nil {
				Result = &Policyfile{
					DefaultSources: []*berkshelf.SourceLocation{},
					Cookbooks:      []*CookbookDef{},
				}
			}
			if yyDollar[1].source != nil {
				Result.DefaultSources = append(Result.DefaultSources, yyDollar[1].source)
			}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:86
		{
			if Result == nil {
				Result = &Policyfile{
					DefaultSources: []*berkshelf.SourceLocation{},
					Cookbooks:      []*CookbookDef{},
				}
			}
			if yyDollar[1].cookbook != nil {
				Result.Cookbooks = append(Result.Cookbooks, yyDollar[1].cookbook)
			}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line policyfile.y:102
		{
			yyVAL.source = yyDollar[2].source
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:108
		{
			sourceType := strings.TrimPrefix(yyDollar[1].str, ":")
			switch sourceType {
			case "supermarket":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "supermarket",
					URL:  "https://supermarket.chef.io",
				}
			case "chef_server":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "chef_server",
				}
			case "chef_repo":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "path",
				}
			case "artifactory":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "supermarket", // Treat as supermarket-like
				}
			default:
				yylex.Error("unsupported source type: " + sourceType)
				yyVAL.source = nil
			}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line policyfile.y:134
		{
			sourceType := strings.TrimPrefix(yyDollar[1].str, ":")
			uri := strings.Trim(yyDollar[3].str, "\"'")

			switch sourceType {
			case "supermarket":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "supermarket",
					URL:  uri,
				}
			case "chef_server":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "chef_server",
					URL:  uri,
				}
			case "chef_repo":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "path",
					Path: uri,
				}
			case "artifactory":
				yyVAL.source = &berkshelf.SourceLocation{
					Type: "supermarket", // Treat as supermarket-like
					URL:  uri,
				}
			default:
				yylex.Error("unsupported source type: " + sourceType)
				yyVAL.source = nil
			}
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:167
		{
			yyVAL.str = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line policyfile.y:173
		{
			name := strings.Trim(yyDollar[2].str, "\"'")
			yyVAL.cookbook = &CookbookDef{
				Name: name,
			}
		}
	case 13:
		yyDollar = yyS[yypt-4 : yypt+1]
//line policyfile.y:180
		{
			name := strings.Trim(yyDollar[2].str, "\"'")
			yyVAL.cookbook = &CookbookDef{
				Name:       name,
				Constraint: yyDollar[4].constraint,
			}
		}
	case 14:
		yyDollar = yyS[yypt-4 : yypt+1]
//line policyfile.y:188
		{
			name := strings.Trim(yyDollar[2].str, "\"'")
			source := createSourceFromOptions(yyDollar[4].options)
			yyVAL.cookbook = &CookbookDef{
				Name:   name,
				Source: source,
			}
		}
	case 15:
		yyDollar = yyS[yypt-6 : yypt+1]
//line policyfile.y:197
		{
			name := strings.Trim(yyDollar[2].str, "\"'")
			source := createSourceFromOptions(yyDollar[6].options)
			yyVAL.cookbook = &CookbookDef{
				Name:       name,
				Constraint: yyDollar[4].constraint,
				Source:     source,
			}
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:209
		{
			yyVAL.options = yyDollar[1].options
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line policyfile.y:215
		{
			yyVAL.options = map[string]string{yyDollar[1].str: yyDollar[3].str}
		}
	case 18:
		yyDollar = yyS[yypt-5 : yypt+1]
//line policyfile.y:219
		{
			yyDollar[1].options[yyDollar[3].str] = yyDollar[5].str
			yyVAL.options = yyDollar[1].options
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:226
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:232
		{
			yyVAL.str = strings.Trim(yyDollar[1].str, "\"'")
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line policyfile.y:238
		{
			constraintStr := strings.Trim(yyDollar[1].str, "\"'")
			constraint, err := berkshelf.NewConstraint(constraintStr)
			if err != nil {
				yylex.Error("invalid version constraint: " + constraintStr)
				yyVAL.constraint = nil
			} else {
				yyVAL.constraint = constraint
			}
		}
	}
	goto yystack /* stack new state and value */
}
